// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmbizatprlbluajrgkkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtYml6YXRwcmxibHVhanJna2trIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5ODk3MDUsImV4cCI6MjA3NDU2NTcwNX0.ce5gDKFQohgI2sx9sxyRRFTgyRhPKfquKat1iiPr1OI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});